---
title: "EHR Project"
author: "Alisha Dziarski, Kari Guo & Susie Wang"
output: html_document
date: "`r Sys.Date()`"
---

```{r Setup}
library(tidyverse)
library(lubridate)
library(survival)
library(epiR)
library(epiDisplay)
library(cmprsk)
library(ggplot2)
```

```{r Data Import}
hosp <- read.csv("hospitalisation_2018-2020.csv")
pres <- read.csv("prescription_2018-2020.csv")
diab_h <- read.csv("diabetes_hosp_2018-2020.csv")
diab_l <- read.csv("diabetes_lti_2018-2020.csv")
```

```{r Data Cleaning}
## Convert date columns to date format---------------------------------

# Diabetic patients
diab_h$HOSP_START_DATE <- date(diab_h$HOSP_START_DATE)
diab_h$HOSP_END_DATE <- date(diab_h$HOSP_END_DATE)

diab_l$LTI_START_DATE <- date(diab_l$LTI_START_DATE)
diab_l$LTI_END_DATE <- date(diab_l$LTI_END_DATE)

# ALL prescriptions
pres$PRS_DATE <- date(pres$PRS_DATE)

# ALL Hospitalizations
hosp$HOSP_START_DATE <- date(hosp$HOSP_START_DATE)
hosp$HOSP_END_DATE <- date(hosp$HOSP_END_DATE)

# Check that format of these columns are now dates
class(diab_h$HOSP_START_DATE)
class(diab_h$HOSP_END_DATE)
class(diab_l$LTI_START_DATE)
class(diab_l$LTI_END_DATE)
class(pres$PRS_DATE)
class(hosp$HOSP_START_DATE)
class(hosp$HOSP_END_DATE)


# Combine T2D patients from LTI and from hospitalizations ------------
diab <- full_join(diab_h, diab_l, by = "PAT_ID")


# New dataframe for diabetes prescriptions ---------------------------
pres_diab <- pres %>% filter(str_detect(DRUG_ATC_C07, "A10A") |
                               str_detect(DRUG_ATC_C07, "A10B"))
table(pres_diab$DRUG_ATC_C07)   # double-check that A10As and A10Bs have been selected
```

## Logistic Regression

```{r Hospitalization}

```


```{r Prescription}

```

## Survival Analysis 

```{r Survival Analysis}

```

## Linear Regression 

```{r Hospitalization}

```

## Mixed Models 

```{r Mixed Models}

```

## Sensitivity Analysis 

```{r Sensitivity Analysis}


```


